# Importing numpy convention

In [126]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (1.18.1)


In [123]:
import numpy as np

In [125]:
np.__version__

'1.18.1'

# Numpy Arrays

In [199]:
np.random.choice([1, 4, 6, 9,])

9

In [147]:
import random

In [171]:
[random.randint(0, 10) for i in range(10)]

[7, 8, 5, 5, 7, 6, 3, 8, 10, 5]

In [172]:
np.random.randint(0, 10, size=10)

array([0, 9, 8, 2, 6, 4, 3, 7, 2, 9])

* 1-D array

In [200]:
np.random.random(10)

array([0.70771655, 0.00891271, 0.60642873, 0.4387842 , 0.81416147,
       0.20411145, 0.35967561, 0.20917073, 0.59726841, 0.99772688])

In [201]:
type(np.random.random(10))

numpy.ndarray

In [206]:
np.random.random(10).shape

(10,)

* 2-D array: **row, column**

In [202]:
np.random.random((5,3))

array([[0.46796805, 0.20957729, 0.12394446],
       [0.45508642, 0.1182027 , 0.8087711 ],
       [0.42150698, 0.5891621 , 0.33208824],
       [0.17657381, 0.93913382, 0.34911347],
       [0.81944433, 0.94884121, 0.37190462]])

In [207]:
a = np.random.random((5,3))

In [209]:
a.shape

(5, 3)

In [210]:
a.size

15

* 3-D array

In [212]:
b = np.random.random((4,2,3))

In [215]:
b

array([[[0.63144361, 0.15232442, 0.05534565],
        [0.52282089, 0.42757474, 0.10096403]],

       [[0.18856645, 0.89899835, 0.2404909 ],
        [0.76870827, 0.39953622, 0.57466798]],

       [[0.27303851, 0.07563403, 0.35055022],
        [0.15537568, 0.14689304, 0.3466432 ]],

       [[0.24550209, 0.90614227, 0.87666896],
        [0.3033357 , 0.80676163, 0.91230566]]])

In [228]:
b[3][0][:2]

array([0.24550209, 0.90614227])

In [221]:
b[:,:,1]

array([[0.15232442, 0.42757474],
       [0.89899835, 0.39953622],
       [0.07563403, 0.14689304],
       [0.90614227, 0.80676163]])

In [229]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [235]:
type(np.ones(7)[0])

numpy.float64

In [240]:
list(range(0,10, 0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [260]:
np.arange(-5,10,0.23, dtype=np.float64)

array([-5.  , -4.77, -4.54, -4.31, -4.08, -3.85, -3.62, -3.39, -3.16,
       -2.93, -2.7 , -2.47, -2.24, -2.01, -1.78, -1.55, -1.32, -1.09,
       -0.86, -0.63, -0.4 , -0.17,  0.06,  0.29,  0.52,  0.75,  0.98,
        1.21,  1.44,  1.67,  1.9 ,  2.13,  2.36,  2.59,  2.82,  3.05,
        3.28,  3.51,  3.74,  3.97,  4.2 ,  4.43,  4.66,  4.89,  5.12,
        5.35,  5.58,  5.81,  6.04,  6.27,  6.5 ,  6.73,  6.96,  7.19,
        7.42,  7.65,  7.88,  8.11,  8.34,  8.57,  8.8 ,  9.03,  9.26,
        9.49,  9.72,  9.95])

In [262]:
np.arange(-5,10,0.23, dtype=np.float32)

array([-5.        , -4.77      , -4.54      , -4.31      , -4.08      ,
       -3.85      , -3.62      , -3.3899999 , -3.1599998 , -2.9299998 ,
       -2.6999998 , -2.4699998 , -2.2399998 , -2.0099998 , -1.7799997 ,
       -1.5499997 , -1.3199997 , -1.0899997 , -0.85999966, -0.62999964,
       -0.39999962, -0.1699996 ,  0.06000042,  0.29000044,  0.52000046,
        0.7500005 ,  0.9800005 ,  1.2100005 ,  1.4400005 ,  1.6700006 ,
        1.9000006 ,  2.1300006 ,  2.3600006 ,  2.5900006 ,  2.8200006 ,
        3.0500011 ,  3.2800007 ,  3.5100002 ,  3.7400007 ,  3.9700012 ,
        4.200001  ,  4.4300003 ,  4.660001  ,  4.8900013 ,  5.120001  ,
        5.3500004 ,  5.580001  ,  5.8100014 ,  6.040001  ,  6.2700005 ,
        6.500001  ,  6.7300014 ,  6.960001  ,  7.1900005 ,  7.420001  ,
        7.6500015 ,  7.880001  ,  8.110001  ,  8.340001  ,  8.570002  ,
        8.800001  ,  9.030001  ,  9.260001  ,  9.490002  ,  9.720001  ,
        9.950001  ], dtype=float32)

# Accessing elements

In [263]:
array_1d = np.random.random(10)

In [264]:
array_1d

array([0.12236851, 0.33190298, 0.75921098, 0.01867442, 0.39236663,
       0.43462119, 0.85951558, 0.44581576, 0.84851747, 0.58713687])

In [265]:
array_2d = np.random.random((5,3))

In [266]:
array_2d

array([[0.85240893, 0.286029  , 0.25901246],
       [0.29447953, 0.65614406, 0.97009007],
       [0.96940429, 0.5391212 , 0.98679268],
       [0.5665003 , 0.6616914 , 0.72489883],
       [0.15933672, 0.92427394, 0.85072887]])

## For 2-D arrays, there are two ways of doing it.

In [267]:
array_2d[0]

array([0.85240893, 0.286029  , 0.25901246])

In [269]:
array_2d[:,1]

array([0.286029  , 0.65614406, 0.5391212 , 0.6616914 , 0.92427394])

In [270]:
array_2d[4,2]

0.8507288722193919

In [271]:
array_2d[4][2]

0.8507288722193919

In [272]:
array_3d = np.random.random((5,3,4))

In [273]:
array_3d

array([[[0.9001524 , 0.64855571, 0.89985191, 0.4804287 ],
        [0.10186745, 0.77351648, 0.99225953, 0.26756626],
        [0.7525239 , 0.43584049, 0.04451847, 0.33967744]],

       [[0.85151038, 0.63501839, 0.16514158, 0.34329856],
        [0.94759048, 0.33807814, 0.66851388, 0.72598678],
        [0.84407828, 0.81521299, 0.42658701, 0.98736627]],

       [[0.47321823, 0.55467605, 0.92805158, 0.53022732],
        [0.75550261, 0.60078805, 0.38982005, 0.64233003],
        [0.79947729, 0.21849259, 0.0247829 , 0.20056837]],

       [[0.06707323, 0.76853499, 0.72331423, 0.35316189],
        [0.78315909, 0.69289646, 0.14426551, 0.42714764],
        [0.91701013, 0.03819109, 0.57999775, 0.02558301]],

       [[0.77058933, 0.7665777 , 0.84591596, 0.43592862],
        [0.26414192, 0.53941842, 0.88864637, 0.93639301],
        [0.28366313, 0.76668754, 0.34962265, 0.62749767]]])

In [274]:
array_3d[4,0,1:3]

array([0.7665777 , 0.84591596])

In [275]:
array_3d[0,2,:]

array([0.7525239 , 0.43584049, 0.04451847, 0.33967744])

# Converting things to np.array

In [277]:
lst = [1,4,7,8]
np.array(lst)


array([1, 4, 7, 8])

In [279]:
print(type(lst), type(np.array(lst)))

<class 'list'> <class 'numpy.ndarray'>


In [281]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
array_lst_lst = np.array(list_of_lists)
array_lst_lst

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [282]:
array_lst_lst.shape

(3, 3)

In [290]:
np.array([[1,3,[5,6,8]]])
[
    [1, 3, [xxxx]]
]

array([[1, 3, list([5, 6, 8])]], dtype=object)

In [289]:
np.array([[1,3,[5,6,8]]]).shape

(1, 3)

In [293]:
np.array([1,'a'])

array(['1', 'a'], dtype='<U21')

# Math functions

## sum

In [385]:
a = np.random.randint(0, 10, size=(3,6))
a

array([[8, 6, 3, 6, 2, 1],
       [8, 7, 8, 7, 5, 3],
       [0, 8, 6, 4, 9, 0]])

In [386]:
# Sum of all elements in matrix a
# Sum of each column in matrix a
# Sum of each row in matrix a
# Sum of all the elements in the first two LINES of matrix a

a.sum()   # soma 
np.sum(a)  # soma 

a.sum(axis=0)

a.sum(axis=1)

a[:2].sum()

64

In [388]:
a

array([[8, 6, 3, 6, 2, 1],
       [8, 7, 8, 7, 5, 3],
       [0, 8, 6, 4, 9, 0]])

In [389]:
y = a[:2]
y

array([[8, 6, 3, 6, 2, 1],
       [8, 7, 8, 7, 5, 3]])

In [326]:
y[0,0] = 10000

In [327]:
y

array([[10000,     6,     2,     2,     8,     5],
       [    3,     3,     8,     0,     8,     3]])

In [328]:
a

array([[10000,     6,     2,     2,     8,     5],
       [    3,     3,     8,     0,     8,     3],
       [    2,     9,     3,     9,     4,     2]])

In [350]:
# shallow (now) copy
lst = [1,3,4]
z = lst

In [357]:
z is lst

True

In [361]:
z == lst 

True

In [358]:
id(z)

4535634432

In [359]:
id(lst)

4535634432

In [360]:
z[0] = 1000

In [362]:
lst

[1000, 3, 4]

In [363]:
# deep (now) copy
lst = [1,3,4]
z = lst.copy()
z[0] = 1000
lst

[1, 3, 4]

In [364]:
z is lst

False

In [365]:
id(z)

4669000768

In [366]:
id(lst)

4665416384

In [371]:
my_lst = [1,3]

print(id(my_lst[0]))
print(id(my_lst[1]))

4363352720
4363352784


In [377]:
my_lst is list

False

In [378]:
my_array = np.array(my_lst)

print(id(my_array[0]))
print(id(my_array[1]))

4664079632
4664079984


In [379]:
a = [1,2,3]

b = a.copy()

In [381]:
a is b

True

In [382]:
a == b

True

In [336]:
z 

[1000, 3, 4]

In [337]:
# deep (now) copy
lst = [1,3,4]
z = lst[:]
z[0] = 1000
lst

[1, 3, 4]

## mean

In [398]:
a

array([[8, 6, 3, 6, 2, 1],
       [8, 7, 8, 7, 5, 3],
       [0, 8, 6, 4, 9, 0]])

In [411]:
# Mean of all elements in matrix a
# Mean of each column in matrix a
# Mean of each row in matrix a
# Mean of all the elements in the first two groups of matrix a

np.mean(a)
# np.mean(a).round()

np.mean(a, axis=0)

a.mean(axis=1)

a[:2].mean()

5.333333333333333

# Operations between np.arrays

In [413]:
a.shape

(3, 6)

In [416]:
a

array([[8, 6, 3, 6, 2, 1],
       [8, 7, 8, 7, 5, 3],
       [0, 8, 6, 4, 9, 0]])

In [414]:
c = np.random.randint(0,10, size=(3,6))
c

array([[1, 5, 4, 9, 3, 1],
       [3, 3, 6, 7, 9, 3],
       [0, 4, 9, 2, 4, 7]])

In [415]:
a + c

array([[ 9, 11,  7, 15,  5,  2],
       [11, 10, 14, 14, 14,  6],
       [ 0, 12, 15,  6, 13,  7]])

In [419]:
a + np.array(b)

ValueError: operands could not be broadcast together with shapes (3,6) (3,) 

In [420]:
a + 1

array([[ 9,  7,  4,  7,  3,  2],
       [ 9,  8,  9,  8,  6,  4],
       [ 1,  9,  7,  5, 10,  1]])

In [421]:
a * 10

array([[80, 60, 30, 60, 20, 10],
       [80, 70, 80, 70, 50, 30],
       [ 0, 80, 60, 40, 90,  0]])

In [423]:
a

array([[8, 6, 3, 6, 2, 1],
       [8, 7, 8, 7, 5, 3],
       [0, 8, 6, 4, 9, 0]])

In [422]:
a * a

array([[64, 36,  9, 36,  4,  1],
       [64, 49, 64, 49, 25,  9],
       [ 0, 64, 36, 16, 81,  0]])

In [430]:
a

array([[8, 6, 3, 6, 2, 1],
       [8, 7, 8, 7, 5, 3],
       [0, 8, 6, 4, 9, 0]])

In [429]:
a.T

array([[8, 8, 0],
       [6, 7, 8],
       [3, 8, 6],
       [6, 7, 4],
       [2, 5, 9],
       [1, 3, 0]])

In [431]:
np.matmul(a,a.T)

array([[150, 185, 108],
       [185, 260, 177],
       [108, 177, 197]])

In [433]:
a / a

<ipython-input-433-bb29898574ab>:1: RuntimeWarning: invalid value encountered in true_divide
  a / a


array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [nan,  1.,  1.,  1.,  1., nan]])

# Reshaping arrays

In [434]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [435]:
np.arange(1, 10).shape

(9,)

In [438]:
np.arange(1, 10).T.shape

(9,)

In [443]:
x = np.random.randint(1, 10, size=(3,4,5))
x

array([[[4, 5, 8, 6, 8],
        [9, 2, 7, 7, 8],
        [1, 2, 1, 7, 3],
        [2, 5, 1, 9, 2]],

       [[2, 2, 4, 7, 5],
        [8, 1, 3, 8, 5],
        [4, 8, 4, 2, 7],
        [2, 5, 5, 3, 3]],

       [[8, 6, 1, 4, 9],
        [2, 8, 7, 4, 7],
        [4, 4, 5, 6, 2],
        [2, 5, 9, 8, 6]]])

In [444]:
x

array([[[4, 5, 8, 6, 8],
        [9, 2, 7, 7, 8],
        [1, 2, 1, 7, 3],
        [2, 5, 1, 9, 2]],

       [[2, 2, 4, 7, 5],
        [8, 1, 3, 8, 5],
        [4, 8, 4, 2, 7],
        [2, 5, 5, 3, 3]],

       [[8, 6, 1, 4, 9],
        [2, 8, 7, 4, 7],
        [4, 4, 5, 6, 2],
        [2, 5, 9, 8, 6]]])

In [445]:
x.T #.transpose()

array([[[4, 2, 8],
        [9, 8, 2],
        [1, 4, 4],
        [2, 2, 2]],

       [[5, 2, 6],
        [2, 1, 8],
        [2, 8, 4],
        [5, 5, 5]],

       [[8, 4, 1],
        [7, 3, 7],
        [1, 4, 5],
        [1, 5, 9]],

       [[6, 7, 4],
        [7, 8, 4],
        [7, 2, 6],
        [9, 3, 8]],

       [[8, 5, 9],
        [8, 5, 7],
        [3, 7, 2],
        [2, 3, 6]]])

In [436]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Concatenating

In [446]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [449]:
d = np.array([[1,2,3], [1,2]])

In [452]:
id(d[0])

4666382208

In [453]:
id(d[1])

4665995456

In [454]:
id(d)

4660797232

In [461]:
lst = [1,2,3]

In [499]:

e = np.array(lst)
print(id(e[0]), id(e[1]))

4659590736 4659590736


In [500]:

e = np.array(lst)
print(id(e[0]))

4659590736


In [502]:
print(id(e[1]))

4670900048


In [480]:
id(e) - id(e[0])

-107776

In [476]:
id(e[1])

4660820624