# Lab | Numpy Deep Dive

**1\. Import the NUMPY package under the name np.**

In [1]:
import numpy as np;

**2\. Print the NUMPY version and the configuration.**

In [2]:
print(np.version.version);

1.15.4


**3\. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a".**

**Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?**



In [3]:
a = np.random.randint(10, size = (2,3,5));
a = np.random.rand(2,3,5);
a = np.random.random((2,3,5));

There are many ways to generate random samples. More can be found here: [Random sampling with NumPy](https://docs.scipy.org/doc/numpy-1.14.1/reference/routines.random.html)


**4\. Print a.**

In [4]:
print(a);

[[[0.77696988 0.12032273 0.12305088 0.39391472 0.83363364]
  [0.42436559 0.88125104 0.99325706 0.51313627 0.69884689]
  [0.79563218 0.01957651 0.54452805 0.58196781 0.90198341]]

 [[0.26239544 0.55867045 0.62245075 0.20499161 0.82582537]
  [0.04593601 0.54950724 0.22293239 0.128724   0.41394822]
  [0.71514051 0.79908154 0.00219064 0.52223395 0.50567988]]]


**5\. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable "b".**

In [5]:
b = np.ones((5,2,3));

**6\. Print b.**

In [6]:
print(b);

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


**7\. Do a and b have the same size? How do you prove that in Python code?**

Yes, they have the same size.

In [7]:
print(a.size == b.size);

True


**8\. Are you able to add a and b? Why or why not?**

No, because even though they have the same size, they don't have the same shape. The shape of a is (3,2,3,5) while the shape of b is (3,5,2,3).

In [8]:
print(a.shape == b.shape);

False


If we try to add a and b, we get an error.

In [9]:
np.add(a, b);

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

**9\. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".**

In [10]:
print(a.shape, '-', b.shape);

(2, 3, 5) - (5, 2, 3)


In [11]:
c = np.transpose(b, [1, 2, 0]);

In [12]:
print(a.shape, '-', c.shape);

(2, 3, 5) - (2, 3, 5)


**10\. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?**

It works because now the two arrays have the same shape, therefore they can be added.

In [13]:
d = np.add(a,c);

**11\. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.**

The relation between terms in a and d is: 

d[n][m][p] = a[n][m][p] + c[n][m][p] 

when c[n][m][p] = 1, n = {0,1}, m = {0,1,2}, p = {0,1,2,3,4}.

We add one to every element in a. 

In [14]:
print('A');
print(a);
print('D');
print(d);

A
[[[0.77696988 0.12032273 0.12305088 0.39391472 0.83363364]
  [0.42436559 0.88125104 0.99325706 0.51313627 0.69884689]
  [0.79563218 0.01957651 0.54452805 0.58196781 0.90198341]]

 [[0.26239544 0.55867045 0.62245075 0.20499161 0.82582537]
  [0.04593601 0.54950724 0.22293239 0.128724   0.41394822]
  [0.71514051 0.79908154 0.00219064 0.52223395 0.50567988]]]
D
[[[1.77696988 1.12032273 1.12305088 1.39391472 1.83363364]
  [1.42436559 1.88125104 1.99325706 1.51313627 1.69884689]
  [1.79563218 1.01957651 1.54452805 1.58196781 1.90198341]]

 [[1.26239544 1.55867045 1.62245075 1.20499161 1.82582537]
  [1.04593601 1.54950724 1.22293239 1.128724   1.41394822]
  [1.71514051 1.79908154 1.00219064 1.52223395 1.50567988]]]


**12\. Multiply a and c. Assign the result to e.**


In [15]:
e = np.multiply(a,c);

**13\. Does e equal to a? Why or why not?**

Yes. The relation between terms in a and e is: 

e[n][m][p] = a[n][m][p] * c[n][m][p]

when c[n][m][p] = 1, n = {0,1}, m = {0,1,2}, p = {0,1,2,3,4}.

We multiply by 1 every element in a, so the resulting array e should be equal to a.

In [16]:
print(a == e);

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


**14\. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"**

In [17]:
d_max = d.max()
d_min = d.min();
d_mean = d.mean();

In [18]:
print('MAX:  ', d_max);
print('MIN:  ', d_min);
print('MEAN: ', d_mean);

MAX:   1.9932570580660234
MIN:   1.0021906354359817
MEAN:  1.4994048217951923


**15\. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.**

In [19]:
f = np.empty((2, 3, 5), dtype=np.int8);

**16\. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.**

In [25]:
it = np.nditer(d, flags=['multi_index']);
while not it.finished:
    if it[0] == d_min:
        f[it.multi_index] = 0;
    elif it[0] > d_min and it[0] < d_mean:
        f[it.multi_index] = 25;
    elif it[0] == d_mean:
        f[it.multi_index] = 50;
    elif it[0] > d_mean and it[0] < d_max:
        f[it.multi_index] = 75;
    else:
        f[it.multi_index] = 100;
    it.iternext()

**17\. Print d and f. Do you have your expected f?**

Yes!

In [21]:
print('D');
print(d);
print('F');
print(f);

D
[[[1.77696988 1.12032273 1.12305088 1.39391472 1.83363364]
  [1.42436559 1.88125104 1.99325706 1.51313627 1.69884689]
  [1.79563218 1.01957651 1.54452805 1.58196781 1.90198341]]

 [[1.26239544 1.55867045 1.62245075 1.20499161 1.82582537]
  [1.04593601 1.54950724 1.22293239 1.128724   1.41394822]
  [1.71514051 1.79908154 1.00219064 1.52223395 1.50567988]]]
F
[[[ 75  25  25  25  75]
  [ 25  75 100  75  75]
  [ 75  25  75  75  75]]

 [[ 25  75  75  25  75]
  [ 25  75  25  25  25]
  [ 75  75   0  75  75]]]


**18\. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements?**

In [22]:
g = np.empty((2, 3, 5), dtype=str);
it = np.nditer(d, flags=['multi_index']);
while not it.finished:
    if it[0] == d_min:
        g[it.multi_index] = 'A';
    elif it[0] > d_min and it[0] < d_mean:
        g[it.multi_index] = 'B';
    elif it[0] == d_mean:
        g[it.multi_index] = 'C';
    elif it[0] > d_mean and it[0] < d_max:
        g[it.multi_index] = 'D';
    else:
        g[it.multi_index] = 'E';
    it.iternext()

In [23]:
print('G');
print(g);

G
[[['D' 'B' 'B' 'B' 'D']
  ['B' 'D' 'E' 'D' 'D']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'D' 'D' 'B' 'D']
  ['B' 'D' 'B' 'B' 'B']
  ['D' 'D' 'A' 'D' 'D']]]
